name: Build Hotspot Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install necessary tools
        run: sudo apt-get update && sudo apt-get install -y opkg-tools

      - name: Run build script
        run: ./build.sh
        working-directory: ./hotspot-pkg

      - name: Upload IPK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: hotspot-ipk
          path: hotspot-pkg/output/packages/*.ipk
