name: Build OpenWrt IPK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install opkg-build
        run: sudo apt-get update && sudo apt-get install -y opkg-tools

      - name: Run Build Script
        run: ./build.sh

      - name: Upload IPK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hotspot-themes-ipk
          path: output/packages/*.ipk
